name: 'my first container action'
description: 'A Security Chef'
author: 'Swapnil Pawar'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Awesome Chef'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
